# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [4]:
# Your code here
import numpy as np
A = np.random.randint(0,100, size=[3,3])
B = np.random.randint(0,100, size=[3,3])
C = np.random.randint(0,100, size=[3,3])

print(A.dot(B+C))
print(A.dot(B) + A.dot(C))

[[14064 11433  8526]
 [24684 22193  9643]
 [11265  9203  8637]]
[[14064 11433  8526]
 [24684 22193  9643]
 [11265  9203  8637]]


## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [5]:
# Your code here 
print(A.dot(B.dot(C)))
print((A.dot(B)).dot(C))

[[ 649815  567831  831516]
 [1198577 1042931 1644177]
 [ 528005  465116  660118]]
[[ 649815  567831  831516]
 [1198577 1042931 1644177]
 [ 528005  465116  660118]]


## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [6]:
# Your code here 
print(A.dot(B))
print(B.dot(A))

[[ 7605  5703  1190]
 [13757 11968  1357]
 [ 5907  4526  1284]]
[[ 6540  3677  3038]
 [ 8419  4293  5609]
 [14321  6718 10024]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [4]:
# Your code here 
print()

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [5]:
# Your code here 

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 